name: CI Build

on:
  push:
    branches: [ "C-M-Y" ]
  pull_request:
    branches: [ "C-M-Y" ]
  workflow_dispatch:

jobs:
  try_to_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Change VersionName to Nightly Version
        run: |
          sed -i 's/\(version = ".*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})"/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')"/' build.gradle
      - name: Build CI Version
        run: chmod 0777 ./gradlew && ./gradlew proguard
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HYDragon-CI
          compression-level: 9
          path: build/libs/hydragon-minsize.jar